services:
  db:
    build: ./db
    container_name: db-service
    volumes:
      - ./db/data:/app/data
    environment:
      - DB_SERVICE_PORT=${DB_SERVICE_PORT}
      - DB_SERVICE_HOST=${DB_SERVICE_HOST}
      - DB_PATH=/app/data/app.db
    networks:
      - ft-transcendence

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/public/avatars:/app/public/avatars
    environment:
      - PORT=${BACKEND_PORT}
      - HOST=${BACKEND_HOST}
      - DB_SERVICE_URL=http://db-service:3001
    depends_on:
      - db
    networks:
      - ft-transcendence

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - PORT=${FRONTEND_PORT}
      - HOST=${FRONTEND_HOST}
      - PROXY=${PROXY_URL}
    ports:
      - "8443:443"
    restart: always
    depends_on:
      - backend
    volumes:
      - proxy_certs:/certs
    networks:
      - ft-transcendence

volumes:
  proxy_certs:

networks:
  ft-transcendence:
    driver: bridge
