services:
  backend:
    build: ./backend
    image: t_backend
    container_name: backend
    volumes:
      - ./db:/app/db
    ports:
      - "3000:3000"   # change later?
    environment:
      - PORT=${BACKEND_PORT}
      - HOST=${BACKEND_HOST}
    networks:
      - ft-transcendence
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
            - "*.log"
            - .dockerignore
            - Dockerfile
        - action: rebuild
          path: ./backend/package.json
  frontend:
    build: ./frontend
    image: t_frontend
    container_name: frontend
    ports:
      - "8080:8080"   # change later
    environment:
      - PORT=${FRONTEND_PORT}
      - HOST=${FRONTEND_HOST}
      - GATEWAY=${GATEWAY_URL}
    networks: 
      - ft-transcendence
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - "*.log"
            - .dockerignore
            - Dockerfile
        - action: rebuild
          path: ./frontend/package.json

networks:
  ft-transcendence:
    driver: bridge
