services:
  db:
    build: ./db
    container_name: db-service
    volumes:
      - ./db/data:/app/data
    expose:
      - "3001:3001"
    environment:
      - DB_SERVICE_PORT=${DB_SERVICE_PORT}
      - DB_SERVICE_HOST=${DB_SERVICE_HOST}
      - DB_PATH=/app/data/app.db
    networks:
      - ft-transcendence
    develop:
      watch:
        - action: sync
          path: ./db
          target: /app
          ignore:
            - node_modules/
            - "*.log"
            - .dockerignore
            - Dockerfile
            - data/
        - action: rebuild
          path: ./db/package.json

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "3000:3000"
    environment:
      - PORT=${BACKEND_PORT}
      - HOST=${BACKEND_HOST}
      - DB_SERVICE_URL=http://db-service:3001
    depends_on:
      - db
    networks:
      - ft-transcendence
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
            - "*.log"
            - .dockerignore
            - Dockerfile
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "5173:5173"
    environment:
      - PORT=${FRONTEND_PORT}
      - HOST=${FRONTEND_HOST}
      - PROXY=${PROXY_URL}
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
          ignore: 
            - node_modules/
            - "*.log"
            - .dockerignore
            - Dockerfile
        - path: ./frontend/package.json
          target: /app/package.json
          action: restart
        - path: ./frontend/vite.config.js
          target: /app/vite.config.js
          action: restart
    networks:
      - ft-transcendence

  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "8443:443"
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - proxy_certs:/certs
    networks:
      - ft-transcendence
    develop:
      watch:
        - action: sync
          path: ./proxy/conf
          target: /etc/nginx/conf.d/

volumes:
  proxy_certs:

networks:
  ft-transcendence:
    driver: bridge
