services:
  proxy:
    build: ./proxy
    image: t_proxy
    container_name: proxy
    ports:
      - "443:443"
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      -ft-transcendence

  db:
    build: ./db
    image: t_db
    container_name: db-service
    volumes:
      - ./db/data:/app/data
    ports:
      - "3001:3001"
    environment:
      - DB_SERVICE_PORT=${DB_SERVICE_PORT}
      - DB_SERVICE_HOST=${DB_SERVICE_HOST}
      - DB_PATH=/app/data/app.db
    networks:
      - ft-transcendence
    develop:
      watch:
        - action: sync
          path: ./db
          target: /app
          ignore:
            - node_modules/
            - "*.log"
            - .dockerignore
            - Dockerfile
            - data/
        - action: rebuild
          path: ./db/package.json

  backend:
    build: ./backend
    image: t_backend
    container_name: backend
    ports:
      - "3000:3000"   # change later?
    environment:
      - PORT=${BACKEND_PORT}
      - HOST=${BACKEND_HOST}
      - DB_SERVICE_URL=http://db-service:3001
    depends_on:
      - db
    networks:
      - ft-transcendence
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
            - "*.log"
            - .dockerignore
            - Dockerfile
        - action: rebuild
          path: ./backend/package.json
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
          ignore: 
            - node_modules/
            - "*.log"
            - .dockerignore
            - Dockerfile
        - path: ./frontend/package.json
          target: /app/package.json
          action: restart
        - path: ./frontend/vite.config.js
          target: /app/vite.config.js
          action: restart

networks:
  ft-transcendence:
    driver: bridge
